worker_count = 12

[runtime]
type = "io_uring"
sq_entries = 4096
cq_entries = 8192
buf_ring_size = 16384
buf_size = 8192


[[http.servers]]
server_name = "127.0.0.1"
listen = 8089

[[http.servers.locations]]
matcher = { type = "prefix", path = "/" }

[http.servers.locations.action]
type = "static"
directory = "./public"

[[http.servers.locations]]
matcher = { type = "prefix", path = "/api" }

[http.servers.locations.action]
type = "proxy"
upstream = "http://127.0.0.1:8080"

[[http.servers.locations]]
matcher = { type = "exact", path = "/health" }

[http.servers.locations.action]
type = "response"
status = 200
body = "OK"

[[http.servers]]
server_name = "127.0.0.1"
listen = 8089 # currently same port binding is not supported

[[http.servers.locations]]
matcher = { type = "prefix", path = "/" }

[http.servers.locations.action]
type = "static"
directory = "./public"

[[http.servers.locations]]
matcher = { type = "prefix", path = "/api" }

[http.servers.locations.action]
type = "proxy"
upstream = "http://127.0.0.1:8080"

[[http.servers.locations]]
matcher = { type = "exact", path = "/health" }

[http.servers.locations.action]
type = "response"
status = 200
body = "OK"
