[package]
name = "master"
version = "0.1.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "thwip-main"
path = "src/main.rs"

[dependencies]
# Diğer workspace paketlerimiz
proxy_common = { package = "proxy-common", path = "../../crates/core" }
slave = { path = "../slave" }

# Linux Sistem Çağrıları (Fork ve Waitpid için kritik)
nix = { version = "0.29", features = ["process", "signal"] } 

# Loglama ve Hata Yönetimi
log = "0.4"
env_logger = "0.11"
anyhow = "1.0" # Kolay hata yönetimi için
signal-hook = "0.3"
